### ISSUE TITLE
Electron app starts and closes immediately ,executed the sample Spectron code provided here,test case fails. 

### ISSUE THREAD

**Issue by Bharadwaj108** [electron/spectron#142]
Hello everyone,
I have copy pasted the the code from [https://github.com/electron/spectron](url) and replaced the path of my electron executable. The code starts my electron application and terminates immediately and logs errors. this is **my code**
```
var assert = require('assert');
var Application = require('spectron').Application
describe('Test Suite 1', function () {
    this.timeout(100000)
    beforeEach(function () {
        this.app = new Application({
            path: '/CorumDispense-win32-ia32/CorumDispense.exe'
        })
        return this.app.start()
        //this.app.start()
    })
    afterEach(function () {
        if (this.app && this.app.isRunning()) {
            return this.app.stop()            
        }
    })
    it('Start Dispense', function () {
        return this.app.client.getWindowCount().then(function (count) {
            assert.equal(count, 1)
        })        
    })
})
```
**And this is my output**

```
Test Name:	Test Suite 1 Start Dispense
Test Outcome:	Failed
Result StandardOutput:	
mocha.json options file not found. Using default values: { ui: 'tdd', reporter: 'tap', timeout: 2000 }
1..1
not ok 1 Test Suite 1 Start Dispense
  AssertionError: 2 == 1
      at Object.<anonymous> (SpectronDemo.js:19:20)
      at Object.exec (C:\Bharat\AutomationDemos\NodeJsProject\Lighthouse\Lighthouse\node_modules\webdriverio\build\lib\helpers\safeExecute.js:28:24)
      at Object.resolve (C:\Bharat\AutomationDemos\NodeJsProject\Lighthouse\Lighthouse\node_modules\webdriverio\build\lib\webdriverio.js:189:29)
      at C:\Bharat\AutomationDemos\NodeJsProject\Lighthouse\Lighthouse\node_modules\webdriverio\build\lib\webdriverio.js:487:32
      at _fulfilled (C:\Bharat\AutomationDemos\NodeJsProject\Lighthouse\Lighthouse\node_modules\q\q.js:834:54)
      at self.promiseDispatch.done (C:\Bharat\AutomationDemos\NodeJsProject\Lighthouse\Lighthouse\node_modules\q\q.js:863:30)
      at Promise.promise.promiseDispatch (C:\Bharat\AutomationDemos\NodeJsProject\Lighthouse\Lighthouse\node_modules\q\q.js:796:13)
      at C:\Bharat\AutomationDemos\NodeJsProject\Lighthouse\Lighthouse\node_modules\q\q.js:604:44
      at runSingle (C:\Bharat\AutomationDemos\NodeJsProject\Lighthouse\Lighthouse\node_modules\q\q.js:137:13)
      at flush (C:\Bharat\AutomationDemos\NodeJsProject\Lighthouse\Lighthouse\node_modules\q\q.js:125:13)
# tests 1
# pass 0
# fail 1
```

Can I please get some help here guys. Thanks in advance.
Regards,
Bharadwaj.

**Comment by MarshallOfSound** [comment]
WebView's count as a window.  This isn't an issue with Spectron as far as I can see, rather your test failed?

**Comment by Bharadwaj108** [comment]
Hello MarshallOfSound,
Can you please elaborate your query. I am sorry I am a total beginner in this area of Spectron-electron,Node.js environment. Whats happening is the app built using electron which sits in C:\CorumDispense-win32-ia32\CorumDispense.exe opens and with in fraction of seconds closes. I just wanted to know the reason why is it terminating abruptly.

**Comment by MarshallOfSound** [comment]
> I just wanted to know the reason why is it terminating abruptly.

Your test is launching the application, running the test and then immediately after the test is complete closing the application with `this.app.stop()`
