### ISSUE TITLE
Bad webdriverio version

### ISSUE THREAD

**Issue by bencon** [electron/spectron#244]
It looks like there have been some recent breaking changes in webdriverio that have caused our automated testing to fail. I was able to get the tests running again by changing this line in the Spectron package.json from "webdriverio": "^4.8.0" to "webdriverio": "4.8.0"

**Comment by watsoncj** [comment]
Confirmed this fixes the issue for me as well.

Error was:
```
    TypeError: this.writeStream.write is not a function
        at Logger.write (/project/node_modules/webdriverio/build/lib/utils/Logger.js:173:34)
        at Logger.log (/project/node_modules/webdriverio/build/lib/utils/Logger.js:197:22)
        at Logger.command (/project/node_modules/webdriverio/build/lib/utils/Logger.js:211:22)
        at EventEmitter.<anonymous> (/project/node_modules/webdriverio/build/lib/utils/Logger.js:78:23)
        at emitOne (events.js:96:13)
        at EventEmitter.emit (events.js:188:7)
        at RequestHandler.create (/project/node_modules/webdriverio/build/lib/utils/RequestHandler.js:211:31)
        at Object.init (/project/node_modules/webdriverio/build/lib/protocol/init.js:57:32)
        at Object.exec (/project/node_modules/webdriverio/build/lib/helpers/safeExecute.js:28:24)
        at Object.resolve (/project/node_modules/webdriverio/build/lib/webdriverio.js:190:29)
```

**Comment by mbaer3000** [comment]
I just ran into this issue today, too. Wouldn't it be useful for spectron to add a shrinkwrap or package-lock file to prevent such issues in the future?

**Comment by pkuca** [comment]
Confirmed our team having the exact same issue, @bencon fix worked.

**Comment by bencon** [comment]
Fixes were committed to the webdriverio repository, and now Spectron is working again as is (without the package.json hack). Therefore, I'm going to close this issue.
