### ISSUE TITLE
Error: Generated checksum for "chromedriver-v1.8.0-win32-x64.zip" did not match expected checksum.

### ISSUE THREAD

**Issue by alexiej** [electron/spectron#266]
When I try install spectrion I've got this issue:

  if (err != null) throw err
                   ^

Error: Generated checksum for "chromedriver-v1.8.0-win32-x64.zip" did not match expected checksum.
    at Hash.hasher.on (C:\PUBLIC\PROJECTS\ELECTRON-CLEAR\vue-test\node_modules\sumchecker\index.js:151:20)
    at Hash.emit (events.js:160:13)
    at emitReadable_ (_stream_readable.js:520:10)
    at emitReadable (_stream_readable.js:514:7)
    at addChunk (_stream_readable.js:280:7)
    at readableAddChunk (_stream_readable.js:256:11)
    at Hash.Readable.push (_stream_readable.js:213:10)
    at Hash.Transform.push (_stream_transform.js:146:32)
    at Hash._flush (internal/crypto/hash.js:43:8)
    at Hash.prefinish (_stream_transform.js:136:10)
npm WARN vue-test@0.0.0 No repository field.
npm WARN vue-test@0.0.0 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-chromedriver@1.8.0 install: `node ./download-chromedriver.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-chromedriver@1.8.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by DarrenCook** [comment]
The same on Linux (npm@5.6.0, node@v8.9.4). E.g. from a fresh project, no node_modules directory:

    npm install spectron@3.8.0 --save-dev

It does `npm install spectron@3.8.0 --save-dev` which fails with:

    Error: Generated checksum for "chromedriver-v1.8.0-linux-x64.zip" did not match expected checksum.

I've tried all kinds of things, and cannot find anyway to work around this. It appears impossible to install the latest version of Spectron?!  (At least using npm.) Can anyone post steps to somehow force an install?

**Comment by alexiej** [comment]
Issue resolved after removing files from ~AppData\Local\Electron\Cashe

Resolution can be found at the link:
https://github.com/electron/spectron/issues/265

#265
