### ISSUE TITLE
Support headless Electron.

### ISSUE THREAD

**Issue by burtonator** [electron/spectron#323]
With more recent Electron versions headless execution should be supported.

At the very minimum we could just not show the window. This would work out well for desktops where the developer doesn't want windows constantly popping up.

Headless seems to work just fine in my tests which wouldn't require Xvfb or other hacks.

**Comment by koalalorenzo** [comment]
I am having `ChromeDriver did not start within 5000ms` error even if Xvfb is running in the docker container. 

It would be nice to have also some example on how to use it for testing on docker (for example: on GitLab)

**Comment by peterdanis** [comment]
@koalalorenzo try to start just the electron app (like `yarn electron` or `npm run electron`), you may possibly miss a dependency.

**Comment by koalalorenzo** [comment]
When I run it from a docker container:
```
internal/child_process.js:323
    throw errnoException(err, 'spawn');
    ^

Error: spawn Unknown system error -8
    at _errnoException (util.js:992:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at Object.exports.spawn (child_process.js:502:9)
    at Object.<anonymous> (/app/node_modules/electron-prebuilt-compile/lib/cli.js:16:37)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
```
Not sure what that could be...

**Comment by koalalorenzo** [comment]
**Update**: On Ubuntu, it runs perfectly but I still get `ChromeDriver did not start within 5000ms`

**Comment by GreeFine** [comment]
Any progress on the issue  or workaround ?
I also tried with `Xvfb` with no luck, every Dockerfile or post seems to be out of date and not working anymore, if someone a "recent" working example it would be very helpful

**Comment by peterdanis** [comment]
I am using Puppeteer instead of Spectron, but maybe it will help you. In ubuntu container (`ubuntu-latest` image used by Github Action CI/CD) I use following command:
`"xvfb-run --auto-servernum --server-args='-screen 0, 1600x900x24' npm run test"`

For troubleshooting it helps just try to start default Electron app by replacing `nmp run test` with `npx electron`, which should give you some error if virtual screen is not working or some dependency is missing.

Note: Recently (for Electron 9) I had to add `"sudo apt-get install libgbm1"` step before running tests.

I use following script to test simple Electron demo app with Puppeteer on MacOS, Window and Ubuntu via Github Actions: https://github.com/peterdanis/electron-puppeteer-demo/blob/master/.github/workflows/tests.yml

**Comment by GreeFine** [comment]
Thanks @peterdanis i made it work
My issue was with `--no-sandbox` i was running inside docker as **root** and electron won't start if this flag isn't set. i had to add it inside my spectron configuration as follow: 
```js
describe("Application launch", function () {
  this.timeout(10000);

  beforeEach(function () {
    this.app = new Application({
      // Your electron path can be any binary
      // i.e for OSX an example path could be '/Applications/MyApp.app/Contents/MacOS/MyApp'
      // But for the sake of the example we fetch it from our node_modules.
      path: electronPath,
      args: ['--no-sandbox', path.join(__dirname, "..")],
    });
    return this.app.start();
  });
```
I might add that `npx electron  --enable-logging` displays more errors messages

I made a working and simple dockerfile for anyone looking to use one
```Dockerfile
FROM node:slim

RUN apt-get update && \
    apt-get install -y xvfb \
                    libgbm1 \
                    libxss1 \
                    libnss3 \
                    libgtk-3-dev \
                    libasound2-dev \
                    unzip \
                    && rm -rf /var/lib/apt/lists/*
                    
CMD yarn install && xvfb-run --auto-servernum --server-args='-screen 0, 1600x900x24' yarn test
```
